#!/usr/bin/env python3
"""Generate the float32 tanh table used by the Pico inference path."""
import math
from pathlib import Path

output = Path(__file__).with_name("fast_tanh_table.h")
values = [f"{math.tanh(i / 64):.10g}f" for i in range(513)]
values[0] = "0.0f"
output.write_text(
    "// Generated by generate_tanh_table.py.\n"
    "static constexpr float kTanhTable[513] = {\n"
    + "".join("    " + ", ".join(values[i:i + 8]) + ",\n" for i in range(0, 513, 8))
    + "};\n"
)
